# Generated by Django 3.2.16 on 2024-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20241203_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
