# Generated by Django 3.2.16 on 2024-12-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create',
        ),
    ]
